#ifndef TRACELIB_CONFIG_H
#define TRACELIB_CONFIG_H

#define TRACELIB_NAMESPACE_IDENT(x) ea::trace::x
#define TRACELIB_NAMESPACE_BEGIN namespace ea { namespace trace {
#define TRACELIB_NAMESPACE_END } }

#define TRACELIB_DEFAULT_PORT 12382

#define TRACELIB_DEBUG TRACELIB_DEBUG_MSG(0)
#define TRACELIB_ERROR TRACELIB_ERROR_MSG(0)
#define TRACELIB_TRACE TRACELIB_TRACE_MSG(0)
#define TRACELIB_WATCH(vars) TRACELIB_WATCH_MSG(0, vars)
#define TRACELIB_DEBUG_MSG(msg) TRACELIB_VISIT_TRACEPOINT_MSG(TRACELIB_NAMESPACE_IDENT(TracePoint)::DebugPoint, 1, msg)
#define TRACELIB_ERROR_MSG(msg) TRACELIB_VISIT_TRACEPOINT_MSG(TRACELIB_NAMESPACE_IDENT(TracePoint)::ErrorPoint, 1, msg)
#define TRACELIB_TRACE_MSG(msg) TRACELIB_VISIT_TRACEPOINT_MSG(TRACELIB_NAMESPACE_IDENT(TracePoint)::LogPoint, 1, msg)
#define TRACELIB_WATCH_MSG(msg, vars) TRACELIB_VARIABLE_SNAPSHOT_MSG(1, vars, msg)

#endif // !defined(TRACELIB_CONFIG_H)

